name: digital_media_bridge_3
description: "Digital Media Bridge App"
publish_to: 'none'
version: 1.0.0+13

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  animations: ^2.0.7
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/cilutions_background.jpg

flutter_native_splash:
  background_image: assets/cilutions_background.jpg
  color: "#000000"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/icon-ios.png"
  adaptive_icon_foreground: "assets/icon-android.png"
  android: true
  ios: true
  adaptive_icon_background: "#0A55A3"
